# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationOwnerHousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название ТСЖ')),
                ('inn', models.CharField(max_length=40, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=40, verbose_name='КПП')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40, verbose_name='Улица')),
                ('house', models.CharField(max_length=40, verbose_name='Дом')),
                ('post_index', models.CharField(max_length=40, verbose_name='Почтовый Индекс')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Закрыта'), (1, 'Выполняеется'), (2, 'Отложена'), (3, 'Уточение'), (4, 'Пере окрыта')], verbose_name='Состояние запроса')),
                ('text', models.TextField(verbose_name='Текс заявки')),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('association_owner_housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.AssociationOwnerHousing', verbose_name='ТСЖ')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('name', models.CharField(max_length=40, verbose_name='Имя чата')),
                ('link', models.CharField(max_length=160, verbose_name='ссылка')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='domochat.House')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.ModeratorRequest', verbose_name='Заявка')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='association_owner_housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.AssociationOwnerHousing', verbose_name='ТСЖ'),
        ),
    ]
