# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 08:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя чата')),
                ('link', models.CharField(max_length=400, verbose_name='ссылка')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID телеграм чата')),
                ('telegram_chat_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='название чатика в Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='HOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название ТСЖ')),
                ('inn', models.CharField(blank=True, max_length=40, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=40, null=True, verbose_name='КПП')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40, verbose_name='Улица')),
                ('number', models.CharField(max_length=40, verbose_name='Дом')),
                ('post_index', models.CharField(blank=True, max_length=40, null=True, verbose_name='Почтовый Индекс')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('hoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domochat.HOA', verbose_name='ТСЖ')),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('association_owner_housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.HOA', verbose_name='ТСЖ')),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Открыта'), (1, 'Закрыта'), (2, 'Выполняеется'), (3, 'Отложена'), (4, 'Уточение')], default=0, verbose_name='Состояние запроса')),
                ('text', models.TextField(verbose_name='Текст заявки')),
                ('executor', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.Chat', verbose_name='Из какого чата')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='house',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domochat.House'),
        ),
    ]
