# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domochat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название ТСЖ')),
                ('inn', models.CharField(blank=True, max_length=40, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=40, null=True, verbose_name='КПП')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заявки')),
                ('executor', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
            ],
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='house',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='house',
            name='association_owner_housing',
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(max_length=400, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Имя чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_moderators', to='domochat.ModeratorRequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='house',
            name='post_index',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Почтовый Индекс'),
        ),
        migrations.AlterField(
            model_name='moderatoruser',
            name='association_owner_housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.HOA', verbose_name='ТСЖ'),
        ),
        migrations.DeleteModel(
            name='AssociationOwnerHousing',
        ),
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.Chat', verbose_name='Из какого чата'),
        ),
        migrations.AddField(
            model_name='house',
            name='hoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domochat.HOA', verbose_name='ТСЖ'),
        ),
    ]
