# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domochat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='house',
            new_name='house_num',
        ),
        migrations.AlterField(
            model_name='associationownerhousing',
            name='inn',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='associationownerhousing',
            name='kpp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domochat.ModeratorRequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='house',
            name='post_index',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Почтовый Индекс'),
        ),
    ]
