# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domochat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заявки')),
                ('executor', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
            ],
        ),
        migrations.RenameModel(
            old_name='AssociationOwnerHousing',
            new_name='HOA',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat',
            new_name='house',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='number',
            field=models.CharField(default='', max_length=40, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(max_length=400, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Имя чата'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='house',
            name='post_index',
            field=models.CharField(max_length=40, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domochat.Chat', verbose_name='Из какого чата'),
        ),
    ]
