# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Исполнитель'),
        ),
    ]
