# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domochat', '0002_auto_20170527_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domochat.ModeratorRequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='house',
            name='association_owner_housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domochat.AssociationOwnerHousing', verbose_name='ТСЖ'),
        ),
    ]
